spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory-route
              uri: http://localhost:8082
              predicates:
                - Path=/api/products/**
            - id: customer-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/customers/**
