spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory-route
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/products/**
            - id: customer-route
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/customers/**